[package]
name = "darvis"
version = "0.1.0"
authors = ["TJ Chase <tbchase@buffalo.edu>"]
edition = "2018"

[dependencies]
opencv = "0.53"
abow = {version = "*", default-features = false, features = ["bincode"]}
nalgebra = "*"
glob = "*"
serde = "*"
axiom = "*"
log = "*"
env_logger = "*"