[package]
name = "darvis"
version = "0.1.0"
authors = ["TJ Chase <tbchase@buffalo.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timely = "*"
opencv = {version = "0.49", default-features = false, features = ["contrib", "opencv-34", "buildtime-bindgen"]}