[package]
name = "darvis"
version = "0.1.0"
authors = ["TJ Chase <tbchase@buffalo.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "*"
abow = {version = "*", default-features = false, features = ["bincode"]}
nalgebra = "*"
glob = "*"
serde = "*"
axiom = "*"