master:
       name: manager
       address: localhost
       file: main.rs

modules:
      -
       name: FRAME_LOADER
       file: frameloader
       actor_message: ImagesMsg
       actor_function: frameloader
       address: locahost
       port: !!str 7777
       multithreaded: false
       threads: 1
       possible_paths:
                      - 
                       from: ImageRead
                       to: Initilization
                       input: images
                       output: feature vectors
                      -
                       from: ImageRead
                       to: ImageAlignment
                       input: images
                       output: feature vectors
      -
       name: FEATURE_EXTRACTOR
       file: orb
       actor_message: FrameMsg
       actor_function: orb_extract
       address: locahost
       port: !!str 7777
       multithreaded: false
       threads: 1
       possible_paths:
                      - 
                       from: FRAME_LOADER
                       to: TRACKER
                       input: images
                       output: feature vectors


      -
       name: TRACKER
       file: tracker
       actor_message: TrackerMsgKLT
       actor_function: tracker_klt
       address: localhost
       port: !!str 7778
       multithreaded: false
       threads: 1
       possible_paths:
                     -
                      from: FeatureDetection
                      to: KFDecision
                      input: feature vectors
                      output: frame, feature points

      -
       name: VISUALIZER
       file: vis
       actor_message: VisMsg
       actor_function: vis
       address: localhost
       port: !!str 7779
       multithreaded: false
       threads: 1
       possible_paths:
                     -
                      from: FeatureDetection
                      to: KFDecision
                      input: feature vectors
                      output: frame, feature points
  
