master:
       name: manager
       address: localhost
       file: main.rs

system_settings:
       show_ui: true

      # CAMERA CALIBRATION
       camera_fx: 718.856
       camera_fy: 718.856
       camera_cx: 607.1928
       camera_cy: 185.2157
       camera_k1: 0.0
       camera_k2: 0.0
       camera_p1: 0.0
       camera_p2: 0.0
       camera_width: 1241
       camera_height: 376
       fps: 10.0
       camera_bf: 386.1448
       thdepth: 35
      #  depth_map_factor:
      #  ORB FEATURE DETECTION
       max_features: 2000
       scale_factor: 1.2
       n_levels: 8
       fast_threshold: 20


modules:
      -
       name: FRAME_LOADER
       file: frameloader
       actor_message: ImagesMsg
       actor_function: frameloader
       address: locahost
       port: !!str 7777
       multithreaded: false
       threads: 1
       possible_paths:
                      - 
                       from: ImageRead
                       to: Initilization
                       input: images
                       output: feature vectors
                      -
                       from: ImageRead
                       to: ImageAlignment
                       input: images
                       output: feature vectors
      -
       name: FEATURE_EXTRACTOR
       file: orb
       actor_message: FrameMsg
       actor_function: orb_extract
       address: locahost
       port: !!str 7777
       multithreaded: false
       threads: 1
       possible_paths:
                      - 
                       from: FRAME_LOADER
                       to: TRACKER
                       input: images
                       output: feature vectors


      -
       name: TRACKER
       file: tracker
       actor_message: TrackerMsg
       actor_function: tracker
       address: localhost
       port: !!str 7778
       multithreaded: false
       threads: 1
       possible_paths:
                     -
                      from: FeatureDetection
                      to: KFDecision
                      input: feature vectors
                      output: frame, feature points

      -
       name: VISUALIZER
       file: vis
       actor_message: VisMsg
       actor_function: vis
       address: localhost
       port: !!str 7779
       multithreaded: false
       threads: 1
       possible_paths:
                     -
                      from: FeatureDetection
                      to: KFDecision
                      input: feature vectors
                      output: frame, feature points
  
