[package]
name = "darvis"
version = "0.1.0"
authors = ["TJ Chase <tbchase@buffalo.edu>"]
edition = "2018"


[[bin]]
name = "bindarvis"
path = "src/main.rs"

[lib]
name = "dvcore"
path = "src/dvcore/lib.rs"

[profile.release]
debug = 1

[rust]
debuginfo-level = 1

[env]
IDL_PACKAGE_FILTER = { value = "std_msgs;r2r_minimal_node_msgs" }

[dependencies]
g2o = { path = "../g2o" }
dvos3binding = { path = "../orbslam-bindings" }
once_cell = "0.1.4"
opencv = { version = "0.63.0"}
nalgebra = {version = "*", features = ["serde-serialize"]}
cv-convert = {version = '0.19.0', features = ['opencv_0-63','nalgebra_0-31']}
chrono = { version = "0.4", features = ["serde"] }
glob = "*"
serde = "*"
env_logger = "*"
yaml-rust = "0.4"
lazy_static = "*"
parking_lot = "0.11"
rand = "0.7.3"
cxx = "1.0.80"
array2d = "*"
num-traits = "0.2"
simba = "*"
log = "*"
fern = {version = "0.6", features = ["colored"] }
derivative = "*"
error-chain = "*"
linked-hash-map = "0.5.6"
spin_sleep = "*"
flame = "0.2.2"
flamer = "0.3"
ctrlc = "3.2.3"
rerun = {version = "0.8.1", features=["web_viewer"]}
tokio = { version = "1.24", default-features = false }
downcast-rs = "1.2.0"
