# Validate yaml with: https://yamlchecker.com/

master:
       name: manager
       address: localhost
       file: main.rs

system:
      localization_only_mode: false
      vocabulary_file: "/home/nitin/Downloads/Thesis/ORB_SLAM3/Vocabulary/ORBvoc.txt"
      framesensor: Mono
      imusensor: None

      fps: 1.0
      use_timestamps_file: false # Instead of running at a fixed fps, use timestamps from the dataset

      results_folder: "results"
      trajectory_file_name: "trajectory.txt"
      create_flamegraph: false
      show_visualizer: false
      log_level: debug # options are [trace, debug, info, warn, error]


modules:
      - 
       name: CAMERA
       settings:
          - 
           name: fx
           value: 718.856
           type: f64
          - 
           name: fy
           value: 718.856
           type: f64
          - 
           name: cx
           value: 607.1928
           type: f64
          - 
           name: cy
           value: 185.2157
           type: f64
          - 
           name: k1
           value: 0.0
           type: f64
          - 
           name: k2
           value: 0.0
           type: f64
          - 
           name: p1
           value: 0.0
           type: f64
          - 
           name: p2
           value: 0.0
           type: f64
          - 
           name: k3
           value: 0.0
           type: f64
          - 
           name: width
           value: 1241
           type: i32
          - 
           name: height
           value: 376
           type: i32
          - 
           name: thdepth
           value: 35
           type: i32
          - 
           name: stereo_baseline_times_fx
           value: 386.1448
           type: f64
          - 
           name: stereo_overlapping_begin
           value: 0
           type: i32
          -
           name: stereo_overlapping_end
           value: 1000
           type: i32

      - 
       name: FEATURE_DETECTION
       settings:
          - 
           name: max_features
           value: 2000
           type: i32
          - 
           name: scale_factor
           value: 1.2
           type: f64
          - 
           name: n_levels
           value: 8
           type: i32
          - 
           name: ini_th_fast
           value: 20
           type: i32
          - 
           name: min_th_fast
           value: 7
           type: i32

      -
       name: MATCHER
       settings:
          - 
            name: far_points_threshold
            value: 20.0
            type: f64


actors:
      -
       name: VISUALIZER
       file: visualizer
       receiver_bound: -1
       settings:
          - 
            name: image_draw_type
            value: none # options are [none, plain, features, featuresandmatches]
            type: string
          -
            name: mcap_file_path
            value: "results/out.mcap"
            type: string

      -
       name: TRACKING_FRONTEND
       file: tracking_frontend
       receiver_bound: 1
       settings:
          -

      -
       name: TRACKING_BACKEND
       file: tracking_backend
       receiver_bound: 1
       possible_paths:
                     -
                      from: tracking_frontend
                      to: localmapping
                      input: keypoints, descriptors
                      output: newkeyframe
       settings:
          - 
            name: recently_lost_cutoff
            value: 5
            type: i32
          - 
            name: frames_to_reset_IMU
            value: 30
            type: i32
          - 
            name: insert_KFs_when_lost
            value: true
            type: bool
          - 
            name: min_num_features
            value: 2000
            type: i32

      -
       name: LOOP_CLOSING
       file: loop_closing
       receiver_bound: -1
       possible_paths:
                     -
                      from: tracking_frontend
                      to: localmapping
                      input: keypoints, descriptors
                      output: newkeyframe
       settings:
          - 

      -
       name: LOCAL_MAPPING
       file: local_mapping
       receiver_bound: -1
       possible_paths:
                     -
                      from: tracking_frontend
                      to: localmapping
                      input: keypoints, descriptors
                      output: newkeyframe
       settings:
          - 
            name: recently_lost_cutoff
            value: 5
            type: i32
          - 
            name: insert_KFs_when_lost
            value: true
            type: bool
          - 
            name: min_num_features
            value: 2000
            type: i32
