# Validate yaml with: https://yamlchecker.com/

master:
       name: manager
       address: localhost
       file: main.rs

system:
      localization_only_mode: false
      vocabulary_file: "../Vocabulary/ORBvoc.txt"
      framesensor: Mono
      imusensor: None
      first_actor_name: TRACKING_FRONTEND # Name of actor to kick off pipeline

      # FPS
      fps: 5.0

      # KIMERA
      initial_k: 0 # Start processing dataset from frame initial_k. Useful to skip a bunch of images at the beginning (imu calibration).
      final_k: 0 # Finish processing dataset at frame final_k. Last frame to process (to avoid processing the entire dataset), skip last frames. If set to 0 will process everything. 

      # RESULTS
      results_folder: "results"
      camera_trajectory_file_name: "camera_trajectory.txt"
      keyframe_trajectory_file_name: "keyframe_trajectory.txt"

      # DEBUGGING
      log_level: debug # options are [trace, debug, info, warn, error]
      check_deadlocks: true # Spawns a new thread to check for deadlocks every 2 secs, but slows stuff down.
      # To enable profiling, set features = ["enable"] for tracy-client in Cargo.toml
      # To turn on visualizer, uncomment visualizer actor below

modules:
      - 
        name: FEATURE_DETECTION
        tag: "orbslam feature detection" # options: ["opencv feature detection", "orbslam feature detection", "good features to track"]
        settings:
          - 
            name: max_features
            value: 1000 #1000 in euroc, 2000 in kitti
            type: i32
          - 
            name: ini_features
            value: 5000 # 5000 in euroc, 10000 in kitti
            type: i32
          - 
            name: scale_factor
            value: 1.2
            type: f64
          - 
            name: n_levels
            value: 8
            type: i32
          - 
            name: ini_th_fast
            value: 20
            type: i32
          - 
            name: min_th_fast
            value: 7
            type: i32

      -
        name: FEATURE_MATCHER
        tag: "orbslam feature matching"
        settings:
          - 
            name: far_points_threshold
            value: 20.0
            type: f64
          - 
            name: high_threshold
            value: 100
            type: i32
          - 
            name: low_threshold
            value: 50
            type: i32
          - 
            name: histo_length
            value: 30
            type: i32

      -
        name: FEATURES
        tag: "features"
        settings:
          - 
            name: frame_grid_rows
            value: 48
            type: i32
          - 
            name: frame_grid_cols
            value: 64
            type: i32

      - 
        name: LOOP_DETECTION
        tag: "orbslam3 loop detection"
        settings:
          - 

      - 
        name: LOCAL_MAP_OPTIMIZATION
        tag: "bundle adjustment"
        settings:
          - 
      - 
        name: FULL_MAP_OPTIMIZATION
        tag: "bundle adjustment"
        settings:
          - 

actors:
      -
       name: VISUALIZER
       tag: visualizer
       receiver_bound: -1
       settings:
          -
            name: stream # if true, stream to websocket. if false, save to mcap file
            value: true
            type: bool
          - name: port # port used if streaming
            value: 8765
            type: i32
          - 
            name: image_draw_type
            value: plain # options are [none, plain, features, featuresandmatches]
            type: string
          -
            name: mcap_file_path
            value: "results/out.mcap"
            type: string
          - name: draw_all_mappoints # Not sure this works right now... If true, draws all mappoints in the map. If false, only draws matches and recently created mappoints. Set to false to save space.
            value: false
            type: bool
          - name: draw_local_mappoints # Whether to draw local mappoints (not tracked, but in local map based on local keyframes)
            value: false
            type: bool
          - name: draw_graph # Works but doesn't look good. Need to figure out some nicer way to distribute the points so it's actually readable
            value: true
            type: bool
          - name: draw_only_trajectory
            value: false
            type: bool

      -
       name: TRACKING_FRONTEND
       tag: "orbslam tracking frontend"
       receiver_bound: 1
       settings:
          - 

      -
       name: TRACKING_BACKEND
       tag: "orbslam tracking backend"
       receiver_bound: 5
       settings:
          - 
            name: recently_lost_cutoff
            value: 5
            type: i32
          - 
            name: frames_to_reset_IMU
            value: 30
            type: i32
          - 
            name: insert_KFs_when_lost
            value: true
            type: bool
          - 
            name: min_num_features
            value: 2000
            type: i32
          - 
            name: min_frames_to_insert_kf
            value: 0
            type: i32
          -
            name: max_frames_to_insert_kf
            value: 10
            type: i32

      -
       name: LOCAL_MAPPING
       tag: "orbslam local mapping"
       receiver_bound: 2
       settings:
          - 

      -
       name: LOOP_CLOSING
       tag: "orbslam3 loop closing"
       receiver_bound: -1
       settings:
          - 
