[package]
name = "darvis"
version = "0.1.0"
authors = ["Pranay Meshram <pranaywa@buffalo.edu>"]
edition = "2018"

[dependencies]
libloading = "0.5.2"
plugins_core = { path = "../core" }


glob = "*"

axiom = "*"
log = "*"
env_logger = "*"
