use std::{collections::BTreeMap, borrow::Cow, sync::Arc, fs, io::BufWriter};
use mcap::{Channel, records::MessageHeader, Writer, Schema};
use serde_json::json;


fn main() {
    let mut writer = Writer::new(
        BufWriter::new(fs::File::create("results/out.mcap").unwrap())
    ).unwrap();

    let schema = Schema {
        name: String::from("foxglove.SpherePrimitive"),
        encoding: String::from("jsonschema"),
        data: Cow::Borrowed(SCHEMA.as_bytes()),
    };

    let channel = Channel {
        topic: String::from("/points"),
        schema: Some(Arc::new(schema)),
        message_encoding: String::from("json"),
        metadata: BTreeMap::default()
    };
    let channel_id = writer.add_channel(&channel).unwrap();

    for i in 1..100 {
        let data = json!({
            "pose": {
                "position": {
                    "x": i,
                    "y": 0,
                    "z": 0
                },
                "orientation": {
                    "x": 0,
                    "y": 0,
                    "z": 0,
                    "w": 1.0
                },
            },
            "size": {
                "x": 0.1,
                "y": 0.1,
                "z": 0.1
            },
            "color": {
                "r": 1.0,
                "g": 0.0,
                "b": 0.0,
                "a": 1.0
            }
        });

        println!("publish time {}", i);
        let time_in_nsec = i as u64 * 1000000000;
        writer.write_to_known_channel(
            &MessageHeader {
                channel_id,
                sequence: i,
                log_time: time_in_nsec,
                publish_time: time_in_nsec
            },
            &serde_json::to_vec(&data).unwrap()
        ).unwrap();
    }

    writer.finish().unwrap();
}


static SCHEMA: &'static str = r#"
    {
    "title": "foxglove.SpherePrimitive",
    "description": "A primitive representing a sphere or ellipsoid",
    "$comment": "Generated by https://github.com/foxglove/schemas",
    "type": "object",
    "properties": {
        "pose": {
        "title": "foxglove.Pose",
        "description": "Position of the center of the sphere and orientation of the sphere",
        "type": "object",
        "properties": {
            "position": {
            "title": "foxglove.Vector3",
            "description": "Point denoting position in 3D space",
            "type": "object",
            "properties": {
                "x": {
                "type": "number",
                "description": "x coordinate length"
                },
                "y": {
                "type": "number",
                "description": "y coordinate length"
                },
                "z": {
                "type": "number",
                "description": "z coordinate length"
                }
            }
            },
            "orientation": {
            "title": "foxglove.Quaternion",
            "description": "Quaternion denoting orientation in 3D space",
            "type": "object",
            "properties": {
                "x": {
                "type": "number",
                "description": "x value"
                },
                "y": {
                "type": "number",
                "description": "y value"
                },
                "z": {
                "type": "number",
                "description": "z value"
                },
                "w": {
                "type": "number",
                "description": "w value"
                }
            }
            }
        }
        },
        "size": {
        "title": "foxglove.Vector3",
        "description": "Size (diameter) of the sphere along each axis",
        "type": "object",
        "properties": {
            "x": {
            "type": "number",
            "description": "x coordinate length"
            },
            "y": {
            "type": "number",
            "description": "y coordinate length"
            },
            "z": {
            "type": "number",
            "description": "z coordinate length"
            }
        }
        },
        "color": {
        "title": "foxglove.Color",
        "description": "Color of the sphere",
        "type": "object",
        "properties": {
            "r": {
            "type": "number",
            "description": "Red value between 0 and 1"
            },
            "g": {
            "type": "number",
            "description": "Green value between 0 and 1"
            },
            "b": {
            "type": "number",
            "description": "Blue value between 0 and 1"
            },
            "a": {
            "type": "number",
            "description": "Alpha value between 0 and 1"
            }
        }
        }
    }
    }
"#;



