pub struct VisSchema {
    pub name:  &'static str,
    pub json:  &'static str,
}

pub const VEC2_SCHEMA: VisSchema = VisSchema {
    name: r"foxglove.Vector2",
    json: r#"
        {
        "title": "foxglove.Vector2",
        "description": "A vector in 2D space that represents a direction only",
        "$comment": "Generated by https://github.com/foxglove/schemas",
        "type": "object",
        "properties": {
            "x": {
            "type": "number",
            "description": "x coordinate length"
            },
            "y": {
            "type": "number",
            "description": "y coordinate length"
            }
        }
        }
    "#
};

pub const IMAGE_SCHEMA: VisSchema = VisSchema {
    name: r"foxglove.RawImage",
    json: r#"
        {
        "title": "foxglove.RawImage",
        "description": "A raw image",
        "$comment": "Generated by https://github.com/foxglove/schemas",
        "type": "object",
        "properties": {
            "timestamp": {
            "type": "object",
            "title": "time",
            "properties": {
                "sec": {
                "type": "integer",
                "minimum": 0
                },
                "nsec": {
                "type": "integer",
                "minimum": 0,
                "maximum": 999999999
                }
            },
            "description": "Timestamp of image"
            },
            "frame_id": {
            "type": "string",
            "description": "Frame of reference for the image. The origin of the frame is the optical center of the camera. +x points to the right in the image, +y points down, and +z points into the plane of the image."
            },
            "width": {
            "type": "integer",
            "minimum": 0,
            "description": "Image width"
            },
            "height": {
            "type": "integer",
            "minimum": 0,
            "description": "Image height"
            },
            "encoding": {
            "type": "string",
            "description": "Encoding of the raw image data\n\nSupported values: `8UC1`, `8UC3`, `16UC1`, `32FC1`, `bayer_bggr8`, `bayer_gbrg8`, `bayer_grbg8`, `bayer_rggb8`, `bgr8`, `bgra8`, `mono8`, `mono16`, `rgb8`, `rgba8`, `uyvy` or `yuv422`, `yuyv` or `yuv422_yuy2`"
            },
            "step": {
            "type": "integer",
            "minimum": 0,
            "description": "Byte length of a single row"
            },
            "data": {
            "type": "string",
            "contentEncoding": "base64",
            "description": "Raw image data"
            }
        }
        }
    "#
};

pub const POSE_SCHEMA: VisSchema = VisSchema {
    name: r"foxglove.Pose",
    json: r#"
        {
        "title": "foxglove.Pose",
        "description": "A position and orientation for an object or reference frame in 3D space",
        "$comment": "Generated by https://github.com/foxglove/schemas",
        "type": "object",
        "properties": {
            "position": {
            "title": "foxglove.Vector3",
            "description": "Point denoting position in 3D space",
            "type": "object",
            "properties": {
                "x": {
                "type": "number",
                "description": "x coordinate length"
                },
                "y": {
                "type": "number",
                "description": "y coordinate length"
                },
                "z": {
                "type": "number",
                "description": "z coordinate length"
                }
            }
            },
            "orientation": {
            "title": "foxglove.Quaternion",
            "description": "Quaternion denoting orientation in 3D space",
            "type": "object",
            "properties": {
                "x": {
                "type": "number",
                "description": "x value"
                },
                "y": {
                "type": "number",
                "description": "y value"
                },
                "z": {
                "type": "number",
                "description": "z value"
                },
                "w": {
                "type": "number",
                "description": "w value"
                }
            }
            }
        }
        }
    "#
};


pub const SPHERE_SCHEMA: VisSchema = VisSchema {
    name: r"foxglove.SpherePrimitive",
    json: r#"
        {
        "title": "foxglove.SpherePrimitive",
        "description": "A primitive representing a sphere or ellipsoid",
        "$comment": "Generated by https://github.com/foxglove/schemas",
        "type": "object",
        "properties": {
            "pose": {
            "title": "foxglove.Pose",
            "description": "Position of the center of the sphere and orientation of the sphere",
            "type": "object",
            "properties": {
                "position": {
                "title": "foxglove.Vector3",
                "description": "Point denoting position in 3D space",
                "type": "object",
                "properties": {
                    "x": {
                    "type": "number",
                    "description": "x coordinate length"
                    },
                    "y": {
                    "type": "number",
                    "description": "y coordinate length"
                    },
                    "z": {
                    "type": "number",
                    "description": "z coordinate length"
                    }
                }
                },
                "orientation": {
                "title": "foxglove.Quaternion",
                "description": "Quaternion denoting orientation in 3D space",
                "type": "object",
                "properties": {
                    "x": {
                    "type": "number",
                    "description": "x value"
                    },
                    "y": {
                    "type": "number",
                    "description": "y value"
                    },
                    "z": {
                    "type": "number",
                    "description": "z value"
                    },
                    "w": {
                    "type": "number",
                    "description": "w value"
                    }
                }
                }
            }
            },
            "size": {
            "title": "foxglove.Vector3",
            "description": "Size (diameter) of the sphere along each axis",
            "type": "object",
            "properties": {
                "x": {
                "type": "number",
                "description": "x coordinate length"
                },
                "y": {
                "type": "number",
                "description": "y coordinate length"
                },
                "z": {
                "type": "number",
                "description": "z coordinate length"
                }
            }
            },
            "color": {
            "title": "foxglove.Color",
            "description": "Color of the sphere",
            "type": "object",
            "properties": {
                "r": {
                "type": "number",
                "description": "Red value between 0 and 1"
                },
                "g": {
                "type": "number",
                "description": "Green value between 0 and 1"
                },
                "b": {
                "type": "number",
                "description": "Blue value between 0 and 1"
                },
                "a": {
                "type": "number",
                "description": "Alpha value between 0 and 1"
                }
            }
            }
        }
        }
    "#
};