name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: Dovyski/setup-opencv-action@v1
      with:
        opencv-version: 3.4.0
        opencv-extra-modules : true
        BUILD_opencv_xfeatures2d: ON
        OPENCV_ENABLE_NONFREE: ON
        
    - name: Install dependencies
      run: apt-get install -y wget git cmake clang libclang-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Build doc
      run: cargo doc --lib --no-deps
    - name: Run tests
      run: cargo test --doc -- --skip doc
